default_platform(:android)

platform :android do
  desc "Build release AAB and upload to Closed Testing (Alpha) on Google Play"
  lane :closed do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "./"
    )

    upload_to_play_store(
      track: "alpha",
      release_status: "draft",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
